name: medrepo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  http: ^1.1.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  connectivity_plus: ^6.0.0
  flutter_timezone: ^5.0.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dosage_form/
    - assets/medrepo_logo.svg

# ----------------------------------------------------------
# ðŸŸ¢ NATIVE SPLASH SCREEN CONFIG (Recommended Setup)
# ----------------------------------------------------------
flutter_native_splash:
  color: "#f7f8fc"
  image: assets/splash.png   
  android: true
  ios: true

  android_12:
    image: assets/splash.png
    icon_background_color: "#f7f8fc"
