name: medrepo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dosage_form/

# ----------------------------------------------------------
# ðŸŸ¢ NATIVE SPLASH SCREEN CONFIG (Recommended Setup)
# ----------------------------------------------------------
flutter_native_splash:
  color: "#f7f8fc"        # Your primary green
  image: assets/splash.png   # <-- put your logo here
  android: true
  ios: true

  android_12:
    image: assets/splash.png
    icon_background_color: "#f7f8fc"
